openapi: 3.0.0
info:
  title: Content Feed Api
  version: 1.0.0
  description: Content Feed Api
paths:
  /api/content:
    get:
      summary: Retrieve content data
      tags: [Posts]
      description: Retrieve content data from an external API and process it.
      responses:
        '200':
          description: Successful response with content data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
        '500':
          description: Error response if fetching content fails
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        subtitle:
          type: string
        imageUri:
          type: string
          format: uri
        description:
          type: string
        author:
          type: string
        priority:
          type: integer
        comments:
          type: array
          items:
            $ref: '#/components/schemas/Comment'

    Comment:
      type: object
      properties:
        author:
          type: string
        message:
          type: string

